apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: sge
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      NodePort: 30000 
