apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: sge
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: oni672/clockbox:latest
          name: django
          ports:
            - containerPort: 8000
              name: gunicorn
