name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:${{ github.run_number }}

test_ubuntu:
  name: Test on node ${{ matrix.node_version }} and Ubuntu
  runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v1
    -name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    -name: npm install, build and test
      run:
        npm install
        npm run build --if-present
        npm test

test_windows:
  name: Test on node ${{ matrix.node_version }} and Windows
  runs on: windows_latest
  needs: test_ubuntu
  strategy:
    matrix:
      node_version: ['18']
  steps:
    -uses: actions/checkout@v1
    -name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node_version: ${{ matrix.node_version }}
    -name:
      run:
        npm install
        npm run build --if-present
        npm test
